//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactMgrClient.ContactExample {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ContactManager")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInformation", Namespace="http://schemas.datacontract.org/2004/07/ContactManager")]
    [System.SerializableAttribute()]
    public partial class ContactInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxNum {
            get {
                return this.faxNumField;
            }
            set {
                if ((object.ReferenceEquals(this.faxNumField, value) != true)) {
                    this.faxNumField = value;
                    this.RaisePropertyChanged("faxNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNum {
            get {
                return this.phoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumField, value) != true)) {
                    this.phoneNumField = value;
                    this.RaisePropertyChanged("phoneNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactExample.IContactManager")]
    public interface IContactManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetData", ReplyAction="http://tempuri.org/IContactManager/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetData", ReplyAction="http://tempuri.org/IContactManager/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetNumberOfContacts", ReplyAction="http://tempuri.org/IContactManager/GetNumberOfContactsResponse")]
        int GetNumberOfContacts(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetNumberOfContacts", ReplyAction="http://tempuri.org/IContactManager/GetNumberOfContactsResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfContactsAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IContactManager/GetDataUsingDataContractResponse")]
        ContactMgrClient.ContactExample.CompositeType GetDataUsingDataContract(ContactMgrClient.ContactExample.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IContactManager/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ContactMgrClient.ContactExample.CompositeType> GetDataUsingDataContractAsync(ContactMgrClient.ContactExample.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetClientInformation", ReplyAction="http://tempuri.org/IContactManager/GetClientInformationResponse")]
        ContactMgrClient.ContactExample.ContactInformation GetClientInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetClientInformation", ReplyAction="http://tempuri.org/IContactManager/GetClientInformationResponse")]
        System.Threading.Tasks.Task<ContactMgrClient.ContactExample.ContactInformation> GetClientInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactManagerChannel : ContactMgrClient.ContactExample.IContactManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactManagerClient : System.ServiceModel.ClientBase<ContactMgrClient.ContactExample.IContactManager>, ContactMgrClient.ContactExample.IContactManager {
        
        public ContactManagerClient() {
        }
        
        public ContactManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int GetNumberOfContacts(int value) {
            return base.Channel.GetNumberOfContacts(value);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfContactsAsync(int value) {
            return base.Channel.GetNumberOfContactsAsync(value);
        }
        
        public ContactMgrClient.ContactExample.CompositeType GetDataUsingDataContract(ContactMgrClient.ContactExample.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ContactMgrClient.ContactExample.CompositeType> GetDataUsingDataContractAsync(ContactMgrClient.ContactExample.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ContactMgrClient.ContactExample.ContactInformation GetClientInformation() {
            return base.Channel.GetClientInformation();
        }
        
        public System.Threading.Tasks.Task<ContactMgrClient.ContactExample.ContactInformation> GetClientInformationAsync() {
            return base.Channel.GetClientInformationAsync();
        }
    }
}
